### ISSUE TITLE
Add configuration for blob storage persistence

### ISSUE THREAD

**Issue by yoh1496** [personium/personium-docker#19]
To keep blob data after stopping containers,
add definition of `volumes` in `personium` service.

**Comment by yoh1496** [comment]
How about append below lines to docker-compose.yml

```
# in personium service
  volumes:
    - personium-data:/personium_nfs/personium-core

# in volumes section
  personium-data:
    driver: local
```
